### ISSUE TITLE
Language agnostic test cases

### ISSUE THREAD

**Issue by vektah** [graphql/graphql-js#1339]
I'm currently looking at writing a new parser in golang, and it would be great if we could easily import the tests.

At the moment I'm looking at  [lexer-test.js](https://github.com/graphql/graphql-js/blob/master/src/language/__tests__/lexer-test.js) which currently looks like:

```
  it('records line and column', () => {
    expect(lexOne('\n \r\n \r  foo\n')).to.contain({
      kind: TokenKind.NAME,
      start: 8,
      end: 11,
      line: 4,
      column: 3,
      value: 'foo',
    });
  });
```

Would you be open to a PR that refactors the test cases to use yaml (or json) instead, so they look more like:
```yaml
records line and column:
    input: "\n \r\n \r  foo\n"
    tokens:
      kind: NAME
      start: 8
      end: 11
      line: 4
      column: 3
      value: 'foo'
```

This would enable us to run the test cases from golang, giving us a way to test for spec compliance. The parser and validation tests might also be usable as a spec in the same way.

I'm aware of https://github.com/graphql-cats/graphql-cats but I'm looking for much lower level tests around the lexer/parser, without having to spin up a server.

Related https://github.com/graphql/graphql-js/issues/749
